# Generated by Django 5.2.4 on 2025-07-04 15:24

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('trainer_tier', models.CharField(choices=[('Novice', 'Novice'), ('Elite', 'Elite'), ('Master', 'Master')], default='Novice', max_length=20)),
            ],
        ),
    ]
