# Generated by Django 5.2.4 on 2025-07-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='poke_caught',
            field=models.IntegerField(default=0),
        ),
    ]
