# Generated by Django 5.2.4 on 2025-07-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0002_users_poke_caught'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='Trainer',
        ),
    ]
