# Generated by Django 5.2.4 on 2025-07-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0006_remove_pokemon_num_caught'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='num_caught',
            field=models.IntegerField(default=0),
        ),
    ]
