# Generated by Django 5.2.4 on 2025-07-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0007_pokemon_num_caught'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='img_number',
            field=models.IntegerField(default=25),
        ),
    ]
