# Generated by Django 5.2.4 on 2025-07-06 21:26

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0008_trainer_img_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCaught',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caught_at', models.DateTimeField(auto_now_add=True)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokeapp.pokemon')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokeapp.trainer')),
            ],
            options={
                'unique_together': {('trainer', 'pokemon')},
            },
        ),
    ]
